language: minimal

services:
  - docker

before_install:
- docker pull enterpriseconnect/build:v1.1beta
- docker images

script:
- docker run --network host -v $TRAVIS_BUILD_DIR:/build -e DIND_PATH= -e PLUGINS=plugins -e DIST=dist -e ARTIFACT=ecagent -e API=api -e APIPKG=github.com/Enterprise-Connect/ec-auth-api -e LIBPKG=github.build.ge.com/212359746 -e TLSPLUGINPKG=github.com/Enterprise-Connect/ec-tls-plugin -e VLNPLUGINPKG=github.com/Enterprise-Connect/ec-vln-plugin -e KEPPLUGINPKG=github.com/Enterprise-Connect/ec-kpw-plugin -e TLSPLUGIN=tls -e VLNPLUGIN=vln -e KEPPLUGIN=kepware -e DHOME=github.com/Enterprise-Connect/agent -e ORG=github.com -e INTERNAL_ORG=github.build.ge.com -e GITLAB_URL=$GITLAB_URL -e GITLAB_TKN=$GITLAB_TKN -e GITPUBTKN=$GITPUBTKN -e BRANCH=$TRAVIS_BRANCH -it enterpriseconnect/build:v1.1beta
