language: minimal
if: head_branch =~ ^1.3-b_update$ OR branch = 1.3-b

services:
  - docker
  
env:
  global:
    - LIBTAG="1.3-b.0.reiwa.lib"

before_install:
- docker pull enterpriseconnect/build:v1.2beta
- docker images

script:
- >
  docker run --network host
  -v $TRAVIS_BUILD_DIR:/build
  -e DIND_PATH=
  -e DIST=dist
  -e ARTIFACT=tengu
  -e API=api
  -e LIBPKG=github.com/wzlib
  -e LIBTAG=$LIBTAG
  -e DHOME=github.com/EC-Release/tengu
  -e ORG=github.com
  -e GITLAB_URL=$GITLAB_URL
  -e GITLAB_TKN=$GITLAB_TKN
  -e GITPUBTKN=$GITPUBTKN
  -e SDK_BRANCH=disty
  -e CA_PPRS=$CA_PPRS
  -it enterpriseconnect/build:v1.2beta

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - enterprise-connect@ge.com
    on_success: always  
    on_failure: always
