language: minimal

services:
  - docker

before_install:
- docker pull enterpriseconnect/build:v1.1beta
- docker images

script:
- >
  docker run --network host
  -v $TRAVIS_BUILD_DIR:/build
  -v $TRAVIS_BUILD_DIR/watcher:/go/src/github.com/Enterprise-Connect/agent/watcher
  -e DIND_PATH=
  -e PLUGINS=plugins
  -e DIST=dist
  -e ARTIFACT=agent
  -e API=api
  -e LIBPKG=github.build.ge.com/212359746
  -e LIBTAG=$LIBTAG
  -e TLSPLUGINPKG=github.com/Enterprise-Connect/tls-plg
  -e VLNPLUGINPKG=github.com/Enterprise-Connect/vln-plg
  -e TLSPLUGIN=tls
  -e VLNPLUGIN=vln
  -e DHOME=github.com/Enterprise-Connect/agent
  -e ORG=github.com
  -e GITLAB_URL=$GITLAB_URL
  -e GITLAB_TKN=$GITLAB_TKN
  -e GITPUBTKN=$GITPUBTKN
  -e SDK_BRANCH=v1.1beta
  -it enterpriseconnect/build:v1.1beta

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - prasada.alokam@ge.com
    on_success: always  
    on_failure: always
