language: minimal

services:
  - docker

before_install:
- docker pull enterpriseconnect/build:v1.1beta
- docker images

script:
- >
  docker run --network host
  -v $TRAVIS_BUILD_DIR:/build
  -e DIND_PATH=
  -e PLUGINS=plugins
  -e DIST=dist
  -e ARTIFACT=agent
  -e API=api
  -e LIBPKG=github.com/wzlib
  -e LIBTAG=$LIBTAG
  -e TLSPLUGINPKG=github.com/EC-Release/tls-plg
  -e VLNPLUGINPKG=github.com/EC-Release/vln-plg
  -e TLSPLUGIN=tls
  -e VLNPLUGIN=vln
  -e DHOME=github.com/EC-Release/agent
  -e ORG=github.com
  -e GITLAB_URL=$GITLAB_URL
  -e GITLAB_TKN=$GITLAB_TKN
  -e GITPUBTKN=$GITPUBTKN
  -e SDK_BRANCH=v1.2beta
  -e CA_PPRS=$CA_PPRS
  -it enterpriseconnect/build:v1.1beta

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - enterprise-connect@ge.com
    on_success: always  
    on_failure: always
