name: v1.1beta-ci
on:
  push:
    branches: [ v1beta ]
  pull_request:
    branches: [ v1beta ]
    types: [opened, synchronize]
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1beta
    env:
      LIBTAG: "v1beta.fukuoka.1729.lib"
      BINTAG: "v1beta.fukuoka.1729"
      GITLAB_URL: "gitlab.com/digital-fo/connectivity/enterprise-connect"
    steps:
      - uses: actions/checkout@v2
      - name: dind build
        id: dind-build
        #env:
        run: |
          - >
            docker run --network host
            -v $TRAVIS_BUILD_DIR:/build
            -e DIND_PATH=
            -e PLUGINS=plugins
            -e DIST=dist
            -e ARTIFACT=agent
            -e API=api
            -e LIBPKG=github.com/wzlib
            -e LIBTAG=$LIBTAG
            -e BINTAG=$BINTAG
            -e TLSPLUGINPKG=github.com/EC-Release/tls-plg
            -e VLNPLUGINPKG=github.com/EC-Release/vln-plg
            -e TLSPLUGIN=tls
            -e VLNPLUGIN=vln
            -e DHOME=github.com/EC-Release/agent
            -e ORG=github.com
            -e GITLAB_URL=$GITLAB_URL
            -e GITLAB_TKN=$GITLAB_TKN
            -e GITPUBTKN=$GITPUBTKN
            -e SDK_BRANCH=v1beta
            -e CA_PPRS=$CA_PPRS
            -it enterpriseconnect/build:v1beta
      - name: after merged
        if: github.event_name == 'push'
        id: pr-merged
        run: |
          echo pr has been merged and closed
